apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  annotations:
    higress.io/wasm-plugin-title: request-monitor
  labels:
    higress.io/resource-definer: higress
    higress.io/wasm-plugin-built-in: "false"
    higress.io/wasm-plugin-category: custom
    higress.io/wasm-plugin-name: request-monitor
    higress.io/wasm-plugin-version: 1.0.0
  name: request-monitor-1.0.0
  namespace: higress-system
spec:
  defaultConfig:
    deleteEndpoint: /redis-store/delete
    enabled: true
    serviceName: redis-store.dns
    timeoutMs: 500
    upsertEndpoint: /redis-store/upsert
  defaultConfigDisable: false
  failStrategy: FAIL_OPEN
  imagePullPolicy: UNSPECIFIED_POLICY
  matchRules: []
  phase: UNSPECIFIED_PHASE
  priority: 100
  url: oci://10.25.110.224:30007/approachingai/request-monitor:3.0.0
