apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  annotations:
    higress.io/wasm-plugin-description: Convert request/response headers, request
      query parameters, and request/response body parameters.
    higress.io/wasm-plugin-icon: https://img.alicdn.com/imgextra/i3/O1CN01bAFa9k1t1gdQcVTH0_!!6000000005842-2-tps-42-42.png
    higress.io/wasm-plugin-title: Transformer
    meta.helm.sh/release-name: higress
    meta.helm.sh/release-namespace: higress-system
  labels:
    app.kubernetes.io/managed-by: Helm
    higress.io/resource-definer: higress
    higress.io/wasm-plugin-built-in: "true"
    higress.io/wasm-plugin-category: transform
    higress.io/wasm-plugin-name: transformer
    higress.io/wasm-plugin-version: 1.0.0
  name: transformer-1.0.0
  namespace: higress-system
spec:
  defaultConfig:
    reqRules:
    - headers:
      - fromKey: session-id
        toKey: X-SMG-Routing-Key
      operate: map
  defaultConfigDisable: false
  failStrategy: FAIL_OPEN
  imagePullPolicy: UNSPECIFIED_POLICY
  matchRules:
  - config:
      reqRules:
      - headers:
        - fromKey: x-session-affinity
          toKey: session-id
        - fromKey: x-session-affinity
          toKey: X-SMG-Routing-Key
        operate: map
    configDisable: false
    ingress:
    - glm-changting
  - config:
      reqRules:
      - headers:
        - fromKey: x-session-affinity
          toKey: session-id
        - fromKey: x-session-affinity
          toKey: X-SMG-Routing-Key
        operate: map
    configDisable: false
    ingress:
    - glm-changting-2
  phase: AUTHN
  priority: 410
  url: oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/transformer:2.0.0
