apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: glm-5.1
  namespace: higress-system
spec:
  endpoints:
  - address: glm51-router-4.default.svc.cluster.local
    weight: 38
  - address: glm51-router-1.default.svc.cluster.local
    weight: 40
  - address: glm51-router-3.default.svc.cluster.local
    weight: 40
  - address: glm51-router-2.default.svc.cluster.local
    weight: 39
  hosts:
  - glm-5.1-cluster.local
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 30002
    protocol: HTTP
  resolution: DNS
