apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: kimi-router-ha-se
  namespace: higress-system
spec:
  hosts:
  - kimi-router-ha-cluster.local
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 30002
    protocol: HTTP
  resolution: DNS
