apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: glm-retry-se
  namespace: higress-system
spec:
  hosts:
  - glm-retry-cluster.local
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 30002
    protocol: HTTP
  resolution: DNS
