apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: kimi-2.6
  namespace: higress-system
spec:
  endpoints: []
  hosts:
  - kimi-2.6-cluster.local
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 30002
    protocol: HTTP
  resolution: DNS
