apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test
  namespace: higress-system
spec:
  endpoints:
  - address: mock-a.mock.svc.cluster.local
    weight: 100
  hosts:
  - test-cluster.local
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 30002
    protocol: HTTP
  resolution: DNS
