---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-0-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-0
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-0
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-0-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-0
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-0
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-1-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-1
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-1
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-1-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-1
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-1
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-2-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-2
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-2
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-2-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-2
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-2
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-3-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-3
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-3
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-3-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-3
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-3
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-4-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-4
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-4
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-4-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-4
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-4
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-5-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-5
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-5
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-5-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-5
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-5
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-6-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-6
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-6
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-6-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-6
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-6
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-7-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-7
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-7
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-7-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-7
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-7
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-8-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-8
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-8
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-8-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-8
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-8
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-9-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-9
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-9
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-9-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-9
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-9
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-10-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-10
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-10
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-10-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-10
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-10
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-11-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-11
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-11
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-11-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-11
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-11
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-12-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-12
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-12
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-12-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-12
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-12
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-13-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-13
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-13
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-13-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-13
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-13
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-14-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-14
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-14
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-14-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-14
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-14
    rolebasedgroup.workloads.x-k8s.io/role: prefill

---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-15-decode
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: decode
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-15
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-15
    rolebasedgroup.workloads.x-k8s.io/role: decode
---
apiVersion: v1
kind: Service
metadata:
  name: model-glm51-15-prefill
  namespace: default
  labels:
    rolebasedgroup.workloads.x-k8s.io/role: prefill
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-15
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: glm51-workers-15
    rolebasedgroup.workloads.x-k8s.io/role: prefill
