apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: glm-5.2-router
  namespace: higress-system
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          route:
            name: glm-5.2
    patch:
      operation: MERGE
      value:
        match:
          case_sensitive: true
          prefix: /
        name: glm-5.2
        route:
          cluster: outbound|30002||glm-5.2-cluster.local
          retry_policy:
            host_selection_retry_max_attempts: 30
            retry_host_predicate:
            - name: envoy.retry_host_predicates.previous_hosts
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate
          timeout: 3600s
  priority: 100
  workloadSelector:
    labels:
      app: higress-gateway
